feat: support thorium
chrisgrieser/alfred-chromium-extensions pull request #2
Opened 2024-11-02 01:38 UTC by nicoandmee

## Checklist
- [X] Used only camelCase variable names.
- [X] If functionality is added or modified, also made respective changes to the
  `README.md` and the internal workflow documentation.

Let me know what you think of this. I'm trying to add support for [Thorium](https://thorium.rocks/), a variant of chromium.

2024-11-02 01:42 UTC, chrisgrieser requested changes

2024-11-02 01:42 UTC, chrisgrieser commented on scripts/browser-vars.json
> +			{
Could you not run your formatter on this block of code?

2024-11-02 01:43 UTC, chrisgrieser commented
Formatter issue, otherwise fine.

2024-11-02 05:02 UTC, nicoandmee commented
> Formatter issue, otherwise fine.

Fixed. :+1

2024-11-02 21:04 UTC, chrisgrieser commented
Thanks!

2024-11-02 21:05 UTC, merged

2024-11-03 10:59 UTC, chrisgrieser commented
Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-chromium-extensions/releases/download/1.4.0/alfred-chromium-extensions.alfredworkflow